create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Products are publicly readable" on public.products;

create policy "Products are publicly readable"
on public.products
for select
to anon, authenticated
using (true);

insert into public.products (name, description, price, stock, image_url)
values
  (
    'Trail Runner Pack',
    'Lightweight pack with water-resistant storage for quick climbs.',
    64.99,
    18,
    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62'
  ),
  (
    'Summit Grip Gloves',
    'Breathable gloves with reinforced palms for hill training.',
    24.50,
    42,
    'https://images.unsplash.com/photo-1511556532299-8f662fc26c06'
  ),
  (
    'Climber Hydration Bottle',
    'Insulated stainless bottle designed for long outdoor sessions.',
    19.99,
    35,
    'https://images.unsplash.com/photo-1602143407151-7111542de6e8'
  ),
  (
    'All-Terrain Headlamp',
    'Rechargeable headlamp with adjustable beam and weather sealing.',
    39.00,
    27,
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee'
  )
on conflict do nothing;
