create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.pos_state (
  id bigint generated by default as identity primary key,
  register_key text not null,
  customer_id bigint references public.customers(id) on delete set null,
  cart jsonb not null default '[]'::jsonb,
  payment_method text not null default 'cash' check (payment_method in ('cash', 'card')),
  cash_received numeric(10, 2) not null default 0 check (cash_received >= 0),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.products
add column if not exists description text;

alter table public.products
add column if not exists supplier_id bigint references public.suppliers(id) on delete set null;

alter table public.sales
add column if not exists customer_id bigint references public.customers(id) on delete set null;

alter table public.customers enable row level security;
alter table public.suppliers enable row level security;
alter table public.pos_state enable row level security;

create unique index if not exists customers_email_unique_idx
on public.customers(email)
where email is not null;

create unique index if not exists suppliers_email_unique_idx
on public.suppliers(email)
where email is not null;

create unique index if not exists pos_state_register_key_unique_idx
on public.pos_state(register_key);

create index if not exists products_supplier_id_idx on public.products(supplier_id);
create index if not exists sales_customer_id_idx on public.sales(customer_id);
create index if not exists pos_state_customer_id_idx on public.pos_state(customer_id);

drop policy if exists "Customers are publicly readable" on public.customers;
drop policy if exists "Customers can be created publicly" on public.customers;
drop policy if exists "Suppliers are publicly readable" on public.suppliers;
drop policy if exists "Suppliers can be created publicly" on public.suppliers;
drop policy if exists "POS state is publicly readable" on public.pos_state;
drop policy if exists "POS state can be managed publicly" on public.pos_state;
drop policy if exists "Products can be created publicly" on public.products;
drop policy if exists "Products can be updated publicly" on public.products;

create policy "Customers are publicly readable"
on public.customers
for select
to anon, authenticated
using (true);

create policy "Customers can be created publicly"
on public.customers
for insert
to anon, authenticated
with check (true);

create policy "Suppliers are publicly readable"
on public.suppliers
for select
to anon, authenticated
using (true);

create policy "Suppliers can be created publicly"
on public.suppliers
for insert
to anon, authenticated
with check (true);

create policy "POS state is publicly readable"
on public.pos_state
for select
to anon, authenticated
using (true);

create policy "POS state can be managed publicly"
on public.pos_state
for all
to anon, authenticated
using (true)
with check (true);

create policy "Products can be created publicly"
on public.products
for insert
to anon, authenticated
with check (true);

create policy "Products can be updated publicly"
on public.products
for update
to anon, authenticated
using (true)
with check (true);

insert into public.customers (name, phone, email, notes)
values
  ('Walk-in Customer', null, null, 'Default customer for counter sales'),
  ('Maya Carter', '+1 555 0104', 'maya.carter@example.com', 'Prefers lightweight trail gear'),
  ('Summit Club', '+1 555 0198', 'orders@summitclub.example.com', 'Group purchases and restock orders')
on conflict do nothing;

insert into public.suppliers (name, phone, email, notes)
values
  ('Peakline Supply', '+1 555 0142', 'sales@peakline.example.com', 'Outdoor packs and accessories'),
  ('Ridge Gear Co.', '+1 555 0177', 'orders@ridgegear.example.com', 'Gloves, lamps, and hydration gear')
on conflict do nothing;

update public.products
set supplier_id = (
  select id
  from public.suppliers
  where name = 'Peakline Supply'
  limit 1
)
where name in ('Trail Runner Pack', 'Climber Hydration Bottle')
  and supplier_id is null;

update public.products
set supplier_id = (
  select id
  from public.suppliers
  where name = 'Ridge Gear Co.'
  limit 1
)
where name in ('Summit Grip Gloves', 'All-Terrain Headlamp')
  and supplier_id is null;
