create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  receipt_code text not null unique,
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  tax numeric(10, 2) not null default 0 check (tax >= 0),
  total numeric(10, 2) not null check (total >= 0),
  payment_method text not null check (payment_method in ('cash', 'card')),
  cash_received numeric(10, 2) check (cash_received is null or cash_received >= 0),
  change_due numeric(10, 2) not null default 0 check (change_due >= 0),
  sold_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) generated always as (unit_price * quantity) stored,
  created_at timestamptz not null default now()
);

create index if not exists sale_items_sale_id_idx on public.sale_items(sale_id);
create index if not exists sale_items_product_id_idx on public.sale_items(product_id);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sale_id bigint references public.sales(id) on delete set null,
  movement_type text not null check (movement_type in ('sale', 'restock', 'adjustment')),
  quantity_delta integer not null,
  quantity_after integer check (quantity_after is null or quantity_after >= 0),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists inventory_movements_product_id_idx on public.inventory_movements(product_id);
create index if not exists inventory_movements_sale_id_idx on public.inventory_movements(sale_id);
create index if not exists inventory_movements_created_at_idx on public.inventory_movements(created_at desc);

create table if not exists public.report_snapshots (
  id bigint generated by default as identity primary key,
  report_date date not null unique default current_date,
  gross_sales numeric(12, 2) not null default 0 check (gross_sales >= 0),
  sales_count integer not null default 0 check (sales_count >= 0),
  units_sold integer not null default 0 check (units_sold >= 0),
  inventory_value numeric(12, 2) not null default 0 check (inventory_value >= 0),
  low_stock_count integer not null default 0 check (low_stock_count >= 0),
  out_of_stock_count integer not null default 0 check (out_of_stock_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.report_snapshots enable row level security;

drop policy if exists "Sales are publicly readable" on public.sales;
drop policy if exists "Sales can be created publicly" on public.sales;
drop policy if exists "Sale items are publicly readable" on public.sale_items;
drop policy if exists "Sale items can be created publicly" on public.sale_items;
drop policy if exists "Inventory movements are publicly readable" on public.inventory_movements;
drop policy if exists "Inventory movements can be created publicly" on public.inventory_movements;
drop policy if exists "Report snapshots are publicly readable" on public.report_snapshots;
drop policy if exists "Report snapshots can be managed publicly" on public.report_snapshots;

create policy "Sales are publicly readable"
on public.sales
for select
to anon, authenticated
using (true);

create policy "Sales can be created publicly"
on public.sales
for insert
to anon, authenticated
with check (true);

create policy "Sale items are publicly readable"
on public.sale_items
for select
to anon, authenticated
using (true);

create policy "Sale items can be created publicly"
on public.sale_items
for insert
to anon, authenticated
with check (true);

create policy "Inventory movements are publicly readable"
on public.inventory_movements
for select
to anon, authenticated
using (true);

create policy "Inventory movements can be created publicly"
on public.inventory_movements
for insert
to anon, authenticated
with check (true);

create policy "Report snapshots are publicly readable"
on public.report_snapshots
for select
to anon, authenticated
using (true);

create policy "Report snapshots can be managed publicly"
on public.report_snapshots
for all
to anon, authenticated
using (true)
with check (true);
